### ISSUE TITLE
Is there a document with this code?

### ISSUE THREAD

**Issue by phexic** [rinkstiekema/Table-structure-recognition-from-images#1]

**Comment by rinkstiekema** [comment]
Currently there is not. I'm still working on the code and training several models. Be aware that the repository will change a lot. I will write a document on how to use the code, publish a dataset and publish pretrained models in the next month.

**Comment by rinkstiekema** [comment]
Added a README. May still be plenty of issues when you want to run the code yourself.

**Comment by phexic** [comment]
Great job, expecting you to get the good results~！
